<?php
$DB_NAME = '';
$DSN = 'mysql:host=;port=;dbname=' . $DB_NAME . ';charset=utf8';
$DB_USER_NAME = '';
$DB_USER_PWD = '';

// 쿼리 (EOD 문법 사용시 변수명은 들여쓰기 하지 않는다.)
$SQL_SELECT_TB_USER = <<<EOD
SELECT
    *
FROM
    TB_USER
WHERE
    USER = :USER
    AND PASSWORD = MD5(:PASSWORD)
EOD;

$SQL_INSERT_TB_TX_INFO = <<<EOD
INSERT INTO TB_TX_INFO (
    USA_NUM,
    DEVICE_TYPE,
    IS_USE,
    IS_ONE_WAY,

    ANALOG_IS_USE_1CH,
    ANALOG_NAME_1CH,
    ANALOG_MIN_VOLTAGE_1CH,
    ANALOG_MAX_VOLTAGE_1CH,
    ANALOG_MIN_VALUE_1CH,
    ANALOG_MAX_VALUE_1CH,

    ANALOG_IS_USE_2CH,
    ANALOG_NAME_2CH,
    ANALOG_MIN_VOLTAGE_2CH,
    ANALOG_MAX_VOLTAGE_2CH,
    ANALOG_MIN_VALUE_2CH,
    ANALOG_MAX_VALUE_2CH,

    DIGITAL_IS_USE_1CH,
    DIGITAL_NAME_1CH,
    DIGITAL_MIN_VALUE_1CH,
    DIGITAL_MAX_VALUE_1CH,

    DIGITAL_IS_USE_2CH,
    DIGITAL_NAME_2CH,
    DIGITAL_MIN_VALUE_2CH,
    DIGITAL_MAX_VALUE_2CH,

    SERIAL_IS_USE_1CH,
    SERIAL_NAME_1CH,
    SERIAL_PROTOCOL_1CH,

    BLUETOOTH_IS_USE_1CH,
    BLUETOOTH_NAME_1CH,
    BLUETOOTH_UUID_1CH

) VALUES (
    :USA_NUM,
    :DEVICE_TYPE,
    :IS_USE,
    :IS_ONE_WAY,

    :ANALOG_IS_USE_1CH,
    :ANALOG_NAME_1CH,
    :ANALOG_MIN_VOLTAGE_1CH,
    :ANALOG_MAX_VOLTAGE_1CH,
    :ANALOG_MIN_VALUE_1CH,
    :ANALOG_MAX_VALUE_1CH,

    :ANALOG_IS_USE_2CH,
    :ANALOG_NAME_2CH,
    :ANALOG_MIN_VOLTAGE_2CH,
    :ANALOG_MAX_VOLTAGE_2CH,
    :ANALOG_MIN_VALUE_2CH,
    :ANALOG_MAX_VALUE_2CH,

    :DIGITAL_IS_USE_1CH,
    :DIGITAL_NAME_1CH,
    :DIGITAL_MIN_VALUE_1CH,
    :DIGITAL_MAX_VALUE_1CH,

    :DIGITAL_IS_USE_2CH,
    :DIGITAL_NAME_2CH,
    :DIGITAL_MIN_VALUE_2CH,
    :DIGITAL_MAX_VALUE_2CH,

    :SERIAL_IS_USE_1CH,
    :SERIAL_NAME_1CH,
    :SERIAL_PROTOCOL_1CH,

    :BLUETOOTH_IS_USE_1CH,
    :BLUETOOTH_NAME_1CH,
    :BLUETOOTH_UUID_1CH
)
EOD;

$SQL_SELECT_TB_TX_LIST = <<<EOD
SELECT
    *
FROM
    TB_TX_INFO
ORDER BY DEVICE_TYPE ASC
EOD;

$SQL_SELECT_TB_TX_INFO = <<<EOD
SELECT
    *
FROM
    TB_TX_INFO
WHERE
    SEQ_ID = :SEQ_ID
EOD;

$SQL_UPDATE_TB_TX_INFO = <<<EOD
UPDATE
    TB_TX_INFO
SET
    USA_NUM = :USA_NUM,
    DEVICE_TYPE = :DEVICE_TYPE,
    IS_USE = :IS_USE,
    IS_ONE_WAY = :IS_ONE_WAY,

    ANALOG_IS_USE_1CH = :ANALOG_IS_USE_1CH,
    ANALOG_NAME_1CH = :ANALOG_NAME_1CH,
    ANALOG_MIN_VOLTAGE_1CH = :ANALOG_MIN_VOLTAGE_1CH,
    ANALOG_MAX_VOLTAGE_1CH = :ANALOG_MAX_VOLTAGE_1CH,
    ANALOG_MIN_VALUE_1CH = :ANALOG_MIN_VALUE_1CH,
    ANALOG_MAX_VALUE_1CH = :ANALOG_MAX_VALUE_1CH,

    ANALOG_IS_USE_2CH = :ANALOG_IS_USE_2CH,
    ANALOG_NAME_2CH = :ANALOG_NAME_2CH,
    ANALOG_MIN_VOLTAGE_2CH = :ANALOG_MIN_VOLTAGE_2CH,
    ANALOG_MAX_VOLTAGE_2CH = :ANALOG_MAX_VOLTAGE_2CH,
    ANALOG_MIN_VALUE_2CH = :ANALOG_MIN_VALUE_2CH,
    ANALOG_MAX_VALUE_2CH = :ANALOG_MAX_VALUE_2CH,

    DIGITAL_IS_USE_1CH = :DIGITAL_IS_USE_1CH,
    DIGITAL_NAME_1CH = :DIGITAL_NAME_1CH,
    DIGITAL_MIN_VALUE_1CH = :DIGITAL_MIN_VALUE_1CH,
    DIGITAL_MAX_VALUE_1CH = :DIGITAL_MAX_VALUE_1CH,

    DIGITAL_IS_USE_2CH = :DIGITAL_IS_USE_2CH,
    DIGITAL_NAME_2CH = :DIGITAL_NAME_2CH,
    DIGITAL_MIN_VALUE_2CH = :DIGITAL_MIN_VALUE_2CH,
    DIGITAL_MAX_VALUE_2CH = :DIGITAL_MAX_VALUE_2CH,

    SERIAL_IS_USE_1CH = :SERIAL_IS_USE_1CH,
    SERIAL_NAME_1CH = :SERIAL_NAME_1CH,
    SERIAL_PROTOCOL_1CH = :SERIAL_PROTOCOL_1CH,

    BLUETOOTH_IS_USE_1CH = :BLUETOOTH_IS_USE_1CH,
    BLUETOOTH_NAME_1CH = :BLUETOOTH_NAME_1CH,
    BLUETOOTH_UUID_1CH = :BLUETOOTH_UUID_1CH,

    U_DATE = CURRENT_TIMESTAMP
WHERE
    SEQ_ID = :SEQ_ID
EOD;

$SQL_DELETE_TB_TX_INFO = <<<EOD
DELETE FROM
    TB_TX_INFO
WHERE
    SEQ_ID = :SEQ_ID
    AND DEVICE_TYPE != 0
EOD;

$SQL_SELECT_TB_TX_DATA_COUNT = <<<EOD
SELECT
    COUNT(SEQ_ID) AS COUNT
FROM
    TB_TX_DATA
WHERE
    USA_NUM = :USA_NUM
    AND CHANNEL_NAME = :CHANNEL_NAME
EOD;

$SQL_SELECT_TB_TX_DATA = <<<EOD
SELECT
    *
FROM
    TB_TX_DATA
WHERE
    USA_NUM = :USA_NUM
    AND CHANNEL_NAME = :CHANNEL_NAME
LIMIT :START, :COUNT
EOD;

$SQL_SELECT_TB_TX_DATA_NAME_LIST = <<<EOD
SELECT
    USA_NUM,
    CHANNEL_NAME
FROM
    TB_TX_DATA
GROUP BY USA_NUM, CHANNEL_NAME
EOD;

$SQL_SELECT_TB_SERIAL_DATA_COUNT = <<<EOD
SELECT
    COUNT(SEQ_ID) AS COUNT
FROM
    TB_SERIAL_DATA
WHERE
    USA_NUM = :USA_NUM
    AND CHANNEL_NAME = :CHANNEL_NAME
EOD;

$SQL_SELECT_TB_SERIAL_DATA = <<<EOD
SELECT
    *
FROM
    TB_SERIAL_DATA
WHERE
    USA_NUM = :USA_NUM
    AND CHANNEL_NAME = :CHANNEL_NAME
LIMIT :START, :COUNT
EOD;

$SQL_SELECT_TB_SERIAL_DATA_NAME_LIST = <<<EOD
SELECT
    A.USA_NUM,
    A.CHANNEL_NAME,
    B.VALUE
FROM
    (
        SELECT
            MAX(SEQ_ID) AS SEQ_ID,
            USA_NUM,
            CHANNEL_NAME
        FROM
            TB_SERIAL_DATA
        WHERE
            C_DATE BETWEEN DATE_SUB(NOW(), INTERVAL 1 MONTH) AND NOW()
        GROUP BY USA_NUM, CHANNEL_NAME
    ) A
    JOIN TB_SERIAL_DATA B ON B.SEQ_ID = A.SEQ_ID;
EOD;

$SQL_INSERT_TB_SENSOR_LIST = <<<EOD
INSERT INTO TB_SENSOR_LIST (
    IS_USE,
    NAME,
    CONNECT_TYPE,
    MIN_VOLTAGE,
    MAX_VOLTAGE,
    MIN_VALUE,
    MAX_VALUE,
    PROTOCOL,
    UUID
) VALUE (
    :IS_USE,
    :NAME,
    :CONNECT_TYPE,
    :MIN_VOLTAGE,
    :MAX_VOLTAGE,
    :MIN_VALUE,
    :MAX_VALUE,
    :PROTOCOL,
    :UUID
)
EOD;

$SQL_SELECT_TB_SENSOR_LIST = <<<EOD
SELECT * FROM TB_SENSOR_LIST
EOD;

$SQL_UPDATE_TB_SENSOR_LIST = <<<EOD
UPDATE
    TB_SENSOR_LIST
SET
    IS_USE = :IS_USE,
    NAME = :NAME,
    MIN_VOLTAGE = :MIN_VOLTAGE,
    CONNECT_TYPE = :CONNECT_TYPE,
    MAX_VOLTAGE = :MAX_VOLTAGE,
    MIN_VALUE = :MIN_VALUE,
    MAX_VALUE = :MAX_VALUE,
    PROTOCOL = :PROTOCOL,
    UUID = :UUID,
    U_DATE = CURRENT_TIMESTAMP
WHERE
    SEQ_ID = :SEQ_ID
EOD;

$SQL_DELETE_TB_SENSOR_LIST = <<<EOD
DELETE FROM
    TB_SENSOR_LIST
WHERE
    SEQ_ID = :SEQ_ID
EOD;

$SQL_SELECT_TB_SETUP = <<<EOD
SELECT
    *
FROM
    TB_SETUP
WHERE
    SEQ_ID = 1
EOD;

$SQL_UPDATE_TB_SETUP = <<<EOD
UPDATE
    TB_SETUP
SET
    SERIAL_DEVICE = :SERIAL_DEVICE,
    BAUD_RATE = :BAUD_RATE,
    SERIAL_DEVICE_MCU = :SERIAL_DEVICE_MCU,
    BAUD_RATE_MCU = :BAUD_RATE_MCU,
    REQUEST_INTERVAL = :REQUEST_INTERVAL,
    SDR_CHANNEL = :SDR_CHANNEL,
    SERVER_TYPE = :SERVER_TYPE,
    SERVER_IP = :SERVER_IP,
    SERVER_PORT = :SERVER_PORT,
    SERVER_TOPIC = :SERVER_TOPIC,
    AP_USE = :AP_USE,
    AP_SSID = :AP_SSID,
    AP_PASSWORD = :AP_PASSWORD,
    AP_CHANNEL = :AP_CHANNEL,
    USE_BOOTING_LOG = :USE_BOOTING_LOG,
    USE_MESSAGE_LOG = :USE_MESSAGE_LOG,
    USE_NETWORK_LOG = :USE_NETWORK_LOG,
    U_DATE = CURRENT_TIMESTAMP
WHERE
    SEQ_ID = 1
EOD;
?>